const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

/**
 * MirrorStore — server-side persistence for the Business Mirror.
 *
 * Honest scope: this is a single-file-per-business JSON store on local disk,
 * not a database. It is real persistence (it survives server restarts, and
 * lets an owner return from a different browser/device and recover their
 * Business Mirror by businessId) but it is not multi-instance safe and has
 * no authentication of its own — anyone who knows a businessId can read or
 * write that business's state. See README "Known limitations" for exactly
 * what a production deployment would need instead (a real database plus
 * owner authentication).
 */
class MirrorStore {
  constructor({ dataDir }) {
    this.dataDir = dataDir;
    if (!fs.existsSync(this.dataDir)) {
      fs.mkdirSync(this.dataDir, { recursive: true });
    }
  }

  _fileFor(businessId) {
    // businessId is generated by this server (see createBusiness), never
    // taken as an arbitrary path from the client, so this is safe from
    // path traversal - but we still defensively strip anything unexpected.
    const safe = String(businessId).replace(/[^a-zA-Z0-9_-]/g, '');
    return path.join(this.dataDir, `${safe}.json`);
  }

  createBusiness() {
    const businessId = 'biz_' + crypto.randomBytes(8).toString('hex');
    const mirrorId = 'mirror_' + crypto.randomBytes(8).toString('hex');
    const record = {
      businessId,
      mirrorId,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      state: null,
    };
    fs.writeFileSync(this._fileFor(businessId), JSON.stringify(record, null, 2));
    return { businessId, mirrorId };
  }

  get(businessId) {
    const file = this._fileFor(businessId);
    if (!fs.existsSync(file)) return null;
    try {
      return JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (e) {
      return null;
    }
  }

  save(businessId, state) {
    const existing = this.get(businessId);
    if (!existing) return null;
    existing.state = state;
    existing.updatedAt = new Date().toISOString();
    fs.writeFileSync(this._fileFor(businessId), JSON.stringify(existing, null, 2));
    return existing;
  }
}

module.exports = { MirrorStore };
